const Router = require('express')
const router = new Router()
const teacherRouter = require('./TeacherRouter')
const studentRouter = require('./StudentRouter')
const groupRouter = require('./GroupRouter')
const voucherRouter = require('./VoucherRouter')
const positionsRouter = require('./PositionsRouter')
const subjectRouter = require('./SubjectRouter')
const termRouter = require('./TermRouter')
const markRouter = require('./MarksRouter')
const authController = require('../controller/AuthController')
const authMiddleware = require('../middleware/AuthMiddleware')
const roleMiddleware = require('../middleware/RoleMiddleware')

router.post('/login', authController.login)

router.use('/teachers', authMiddleware, roleMiddleware('ADMIN'), teacherRouter)
router.use('/students', authMiddleware, roleMiddleware( 'ADMIN'), studentRouter)
router.use('/groups', authMiddleware, roleMiddleware('ADMIN'), groupRouter)
router.use('/vouchers', authMiddleware, roleMiddleware('ADMIN'), voucherRouter)
router.use('/subjects', authMiddleware, roleMiddleware('ADMIN'), subjectRouter)
router.use('/terms', authMiddleware, roleMiddleware('ADMIN'), termRouter)
router.use('/positions', authMiddleware, roleMiddleware('ADMIN'), positionsRouter)
router.use('/marks', authMiddleware, roleMiddleware('ADMIN'), markRouter)

module.exports = router